In [3]:
# Video 2 part 1 
from sklearn.datasets import load_iris
iris = load_iris()
print(iris.feature_names)
print(iris.target_names)
print(iris.data[0])
print(iris.target[0])
for i in range(len(iris.target)):
  print ("example %d: label %s, features %s" % (i, iris.target[i], iris.data[i]))

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']
[5.1 3.5 1.4 0.2]
0
example 0: label 0, features [5.1 3.5 1.4 0.2]
example 1: label 0, features [4.9 3.  1.4 0.2]
example 2: label 0, features [4.7 3.2 1.3 0.2]
example 3: label 0, features [4.6 3.1 1.5 0.2]
example 4: label 0, features [5.  3.6 1.4 0.2]
example 5: label 0, features [5.4 3.9 1.7 0.4]
example 6: label 0, features [4.6 3.4 1.4 0.3]
example 7: label 0, features [5.  3.4 1.5 0.2]
example 8: label 0, features [4.4 2.9 1.4 0.2]
example 9: label 0, features [4.9 3.1 1.5 0.1]
example 10: label 0, features [5.4 3.7 1.5 0.2]
example 11: label 0, features [4.8 3.4 1.6 0.2]
example 12: label 0, features [4.8 3.  1.4 0.1]
example 13: label 0, features [4.3 3.  1.1 0.1]
example 14: label 0, features [5.8 4.  1.2 0.2]
example 15: label 0, features [5.7 4.4 1.5 0.4]
example 16: label 0, features [5.4 3.9 1.3 0.4]
example 17: label 0, features [5.1 3.5 1.4 0.3]
example

In [19]:
pip install pydotplus

SyntaxError: invalid syntax (2692274308.py, line 2)

In [20]:
pip install GraphViz

     ---------------------------------------- 47.0/47.0 kB 1.1 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.1
[notice] To update, run: C:\Users\cjeco\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
# video 2 part 2
import numpy as np
from sklearn.datasets import load_iris
from sklearn import tree
iris = load_iris()
test_idx = [0,50,100]

#training data
train_target = np.delete(iris.target, test_idx)
train_data = np.delete(iris.data, test_idx, axis=0)

# testing data
test_target = iris.target[test_idx]
test_data = iris.data[test_idx]

clf = tree.DecisionTreeClassifier()
clf.fit(train_data, train_target)

print(test_target)
print(clf.predict(test_data))

# viz code
from six import StringIO
import pydotplus
dot_data = StringIO()
tree.export_graphviz(clf, out_file=dot_data, feature_names=iris.feature_names,
                     class_names=iris.target_names,
                     filled=True, rounded=True, impurity=False)

graph = pydotplus.graph_from_dot_data(dot_data.getvalue())
graph.write_pdf("iris.pdf")

print(test_data[0], test_target[0])

print(iris.feature_names, iris.target_names)

print(test_data[1], test_target[1])

print(iris.feature_names, iris.target_names)

print(test_data[2], test_target[2])

print(iris.feature_names, iris.target_names)

[0 1 2]
[0 1 2]
[5.1 3.5 1.4 0.2] 0
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
[7.  3.2 4.7 1.4] 1
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
[6.3 3.3 6.  2.5] 2
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)'] ['setosa' 'versicolor' 'virginica']
